### ISSUE TITLE
Syntax highlighting differences between this fork and the original repository

### ISSUE THREAD

**Issue by willwillsiii** [Luxed/ayu-vim#27]
I saw that some colors were updated to match the definitions in the [ayu-colors](https://github.com/ayu-theme/ayu-colors) repository. I'm not sure if this change is due to that, but I've noticed differences in syntax highlighting between this fork and the original:
![image](https://user-images.githubusercontent.com/24965267/224204564-d04204e0-e330-45d6-99f3-5a56f40ed04d.png)
(this fork on right, old on left)

Notice the difference in which variables recieve the blue color. Perhaps I'm just used to it, but I find the old highlighting to be easier to parse.

Was this intentional?

Sorry if this overlaps with the other syntax highlighting issues that are open.

**Comment by Luxed** [comment]
> Was this intentional?

In short, yes.

To explain further, "variables", in my fork, should always be shown as the "normal" color. The blue that was used before is reserved for either "types" or "properties/fields" (slightly different shade).

> Perhaps I'm just used to it

That is often the case. When I make a change, I always make sure to use it myself for a while before pushing it. If I forget about it after a while, it means it's fine, if I don't it means it needs to be changed (which is why #22 is still not merged).
But I you could argue that `g:` is a variable (representing the global dictionary) and `vim_markdown_math` is a property of that dictionary. But the vim syntax files are not good enough to differentiate those, which is why I chose to use the "variable" color instead of the "property" color.

Another thing to note is that I mostly use [treesitter](https://github.com/nvim-treesitter/nvim-treesitter) so I have a tendency to use that as a "source of truth". I've found treesitter to be a lot more consistent across languages than most syntax files.
Still, I'll look into it. If it turns out the vim syntax and treesitter are different, then I'll see what to do. If everything already looks the same, I'll give you a configuration to add to go back to the previous look.

**Comment by willwillsiii** [comment]
For what it's worth, I've tested other themes and they seem to follow the behavior of the original repository.

I've also noticed that if I start vim on a different colorscheme, switch to this colorscheme, and then back to the original, the syntax highlighting of the original colorscheme is affected:

![image](https://user-images.githubusercontent.com/24965267/224476016-6c1e840d-a49c-43a0-903c-59501af74233.png)

(Original gruvbox on left, gruvbox after `colorscheme ayu`)

**Comment by willwillsiii** [comment]
> Still, I'll look into it. If it turns out the vim syntax and treesitter are different, then I'll see what to do. If everything already looks the same, I'll give you a configuration to add to go back to the previous look.

I appreciate the effort!

**Comment by Luxed** [comment]
> I've also noticed that if I start vim on a different colorscheme, switch to this colorscheme, and then back to the original, the syntax highlighting of the original colorscheme is affected

I've tried this with [this gruvbox theme](https://github.com/morhetz/gruvbox) (you didn't give information on _which_ gruvbox theme you are using).
I don't have the issue with Neovim or Vim 9.

> > Still, I'll look into it. If it turns out the vim syntax and treesitter are different, then I'll see what to do. If everything already looks the same, I'll give you a configuration to add to go back to the previous look.
> 
> I appreciate the effort!

![image](https://user-images.githubusercontent.com/10234894/225022707-2f9a30bd-784f-4831-af67-301b9e0ccb60.png)
This is what it looks like with Neovim and TreeSitter. `g:` uses the `@namespace` highlight which makes sense. Anything after is highlighted as a "variable". So I'm now sure that it's not a bug and everything looks exactly as intended.
You can, however, change the highlight for yourself. Since you are using the default vim syntax, you will need to add the following line `call ayu#hi('vimVar', 'syntax_tag', '')`.
For more information on how to customize Ayu, see [this section of the readme](https://github.com/Luxed/ayu-vim#customize-the-theme-to-your-liking) (customizing the theme this way means it won't affect any other theme).

**Comment by willwillsiii** [comment]
>I've tried this with [this gruvbox theme](https://github.com/morhetz/gruvbox) (you didn't give information on which gruvbox theme you are using).
I don't have the issue with Neovim or Vim 9.

Apologies, the issue appears across every colorscheme after loading `ayu.vim`, which I could have made more clear.

The colorscheme mangling [does appear to be a Vim8 bug](https://github.com/altercation/solarized/issues/102) unfortunately. There's a solution in that issue [here](https://github.com/altercation/solarized/issues/102#issuecomment-275269574).

Thanks for the assistance!
